name: Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    name: Build Release
    runs-on: ubuntu-22.04
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🔧 Build and publish .NET application Windows
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: dotnet publish -c Release -r win-x64